# Generated by Django 4.1.3 on 2022-11-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=7)),
                ('course_title', models.TextField()),
                ('course_core_elective', models.CharField(max_length=10)),
                ('course_marks', models.IntegerField()),
                ('course_owner', models.CharField(max_length=40)),
                ('course_reviewer', models.CharField(max_length=40)),
                ('course_mode', models.CharField(max_length=10)),
                ('course_instructor', models.CharField(max_length=40)),
            ],
        ),
    ]
