# Generated by Django 4.1.3 on 2022-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetable',
            name='course_title',
            field=models.CharField(max_length=50),
        ),
    ]
