# Generated by Django 4.1.3 on 2022-12-24 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('que1_a', models.IntegerField(default=0)),
                ('que1_b', models.IntegerField(default=0)),
                ('que1_c', models.IntegerField(default=0)),
                ('que2_a', models.IntegerField(default=0)),
                ('que2_b', models.IntegerField(default=0)),
                ('que2_c', models.IntegerField(default=0)),
                ('que2_d', models.IntegerField(default=0)),
                ('que2_e', models.IntegerField(default=0)),
                ('que3_a', models.IntegerField(default=0)),
                ('que3_b', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
