# Generated by Django 4.1.3 on 2022-12-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalmarks',
            name='co1_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co1_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co1_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co2_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co2_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co2_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co2_d',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co2_e',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co3_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='co3_b',
            field=models.IntegerField(null=True),
        ),
    ]
