# Generated by Django 4.1.3 on 2022-12-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessional', '0002_sessionalmarks_co1_a_sessionalmarks_co1_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(max_length=3)),
                ('total_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SessionalQuestionStudentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessional.question')),
                ('sessional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessional.sessional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SessionalMarks',
        ),
    ]
